# Default values for server-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  tag: "1.0.0"

nameOverride: "indexing-drive-service"
fullnameOverride: "indexing-drive-service"
deployment:
  health:
    enabled: false
    checks:
      livenessProbe:
        httpGet:
          path: /healthcheck
          port: 8081
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /healthcheck
          port: 8081
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
service:
  type: ClusterIP
  port: 8081
  targetPort: 8081

ingress:
  enabled: false

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
   cpu: 200m
   memory: 256Mi
  requests:
   cpu: 100m
   memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
