dependencies:
  - name: drive-ui
    version: 0.1.0
    repository: file://../drive-ui
  - name: api-gateway
    version: 0.1.0
    repository: file://../api-gateway
  - name: delegation-service
    version: 0.1.0
    repository: file://../delegation-service
  - name: download-service
    version: 0.1.0
    repository: file://../download-service
  - name: upload-service
    version: 0.1.0
    repository: file://../upload-service
  - name: file-service
    version: 0.1.0
    repository: file://../file-service
  - name: authentication-service
    version: 0.1.0
    repository: file://../authentication-service
  - name: user-service
    version: 0.1.0
    repository: file://../user-service
  - name: permission-service
    version: 0.1.0
    repository: file://../permission-service
  - name: permit-service
    version: 0.1.0
    repository: file://../permit-service
  - name: test-saml-idp
    version: 0.1.0
    repository: file://../test-saml-idp
  - name: redis
    version: 0.1.0
    repository: file://../redis
  - name: search-service
    version: 0.1.0
    repository: file://../search-service
  - name: spike-service
    version: 0.1.0
    repository: file://../spike-service
  - name: gotenberg
    version: 0.1.0
    repository: file://../gotenberg
  - name: listener-service
    version: 0.1.0
    repository: file://../listener-service
  - name: rabbitmq
    version: 0.1.0
    repository: file://../rabbitmq
  - name: manager-service
    version: 0.1.0
    repository: file://../manager-service
  - name: drive-service
    version: 0.1.0
    repository: file://../drive-service
  - name: delete-service
    version: 0.1.0
    repository: file://../delete-service
  - name: elastic-service
    version: 0.1.0
    repository: file://../elastic-service
  - name: parsing-service
    version: 0.1.0
    repository: file://../parsing-service
  - name: advanced-search-service
    version: 0.1.0
    repository: file://../advanced-search-service
      

  
