dependencies:
  - name: web-ui
    version: 0.1.0
    repository: https://github.com/meateam/drive-project/tree/master/z-helm/web-ui
  - name: api-gateway
    version: 0.1.0
    repository: https://github.com/meateam/drive-project/tree/master/z-helm/api-gateway
  - name: delegation-service
    version: 0.1.0
    repository: https://github.com/meateam/drive-project/tree/master/z-helm/delegation-service
  - name: download-service
    version: 0.1.0
    repository: https://github.com/meateam/drive-project/tree/master/z-helm/download-service
  - name: upload-service
    version: 0.1.0
    repository: https://github.com/meateam/drive-project/tree/master/z-helm/upload-service
  - name: file-service
    version: 0.1.0
    repository: https://github.com/meateam/drive-project/tree/master/z-helm/file-service
  - name: authentication-service
    version: 0.1.0
    repository: https://github.com/meateam/drive-project/tree/master/z-helm/authentication-service
  - name: user-service
    version: 0.1.0
    repository: https://github.com/meateam/drive-project/tree/master/z-helm/user-service
  - name: permission-service
    version: 0.1.0
    repository: https://github.com/meateam/drive-project/tree/master/z-helm/permission-service
  - name: permit-service
    version: 0.1.0
    repository: https://github.com/meateam/drive-project/tree/master/z-helm/permit-service
  - name: test-saml-idp
    version: 0.1.0
    repository: https://github.com/meateam/drive-project/tree/master/z-helm/test-saml-idp
  - name: redis
    version: 0.1.0
    repository: https://github.com/meateam/drive-project/tree/master/z-helm/redis
  - name: search-service
    version: 0.1.0
    repository: https://github.com/meateam/drive-project/tree/master/search-service
  - name: spike-service
    version: 0.1.0
    repository: https://github.com/meateam/drive-project/tree/master/z-helm/spike-service
  - name: gotenberg
    version: 0.1.0
    repository: https://github.com/meateam/drive-project/tree/master/gotenberg
