name: "test-saml-idp"
replicaCount: 1

images:
  PullSecrets: 
    name: test-drive-secret
  repository: drivehub.azurecr.io/meateam/test-saml-idp
  tag: "develop"

service:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080

config:
  configmaps: [global-config]

ingress:
  enabled: true
  hosts:
  - host: drive-test.team-pandora.com
    paths:
      - path: /simplesaml
        service: test-saml-idp
        port: "8080"